// +build !noasm
// Generated by PeachPy 0.2.0 from dot.py


// func Dot(x *float32, y *float32) float32
TEXT ·Dot(SB),4,$0-20
	MOVQ x+0(FP), AX
	MOVQ y+8(FP), BX
	BYTE $0xC5; BYTE $0xF8; BYTE $0x28; BYTE $0x00 // VMOVAPS xmm0, [rax]
	BYTE $0xC5; BYTE $0xF8; BYTE $0x28; BYTE $0x0B // VMOVAPS xmm1, [rbx]
	BYTE $0xC4; BYTE $0xE3; BYTE $0x79; BYTE $0x40; BYTE $0xD1; BYTE $0xFF // VDPPS xmm2, xmm0, xmm1, 255
	MOVSS X2, ret+16(FP)
	BYTE $0xC5; BYTE $0xF8; BYTE $0x77 // VZEROUPPER
	RET
